MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]
folly_build_ext:
  - None
  - "jemalloc"  # [not win]
fmt:
  - "9"
  - "9"
  - "10"
libevent:
  - "2.1.10"
  - "2.1.12"
  - "2.1.12"
zip_keys:
  - fmt
  - libevent
