MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]
folly_build_ext:
  - None
  - "jemalloc"  # [not win]
fmt:
  - "10"
  - "9"
  - "9"
libevent:
  - "2.1.12"
  - "2.1.10"
  - "2.1.12"
# `zip_keys` is bugued
#
# This specification correctly builds for:
#
#     - fmt 9 + libevent 2.1.10
#     - fmt 9 + libevent 2.1.12
#     - fmt 10 + libevent 2.1.12
#
# See: https://github.com/conda-forge/folly-feedstock/pull/136#discussion_r1305820893
zip_keys:
  - fmt
  - libevent
